/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/about/index" |
       "/pages/reportWork/index" |
       "/pages/task/index" |
       "/pages/userCenter/index" |
       "/pages-sub/board/board" |
       "/pages-sub/demo/index" |
       "/pages-sub/info/noGoodClass" |
       "/pages-sub/info/noGoodTotal" |
       "/pages-sub/info/yield" |
       "/pages-sub/inWarehouse/edit" |
       "/pages-sub/inWarehouse/list" |
       "/pages-sub/login/index" |
       "/pages-sub/outWarehouse/edit" |
       "/pages-sub/outWarehouse/list" |
       "/pages-sub/warehouse/check" |
       "/pages-sub/warehouse/list" |
       "/pages-sub/workOrder/detail" |
       "/pages-sub/workOrder/taskDetail" |
       "/pages-sub/device/plan/list";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/task/index" | "/pages/about/index" | "/pages/reportWork/index" | "/pages/userCenter/index"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
